theme = 'mini-bau'
baseURL = 'https://example.org/'
languageCode = 'de'
title = 'RobBau — Bauleistungen aus einer Hand'
header = 'RobBau'
subheader = 'Bauleistungen aus einer Hand'

[[menus.top]]
name = 'Leistungen'
pageRef = '/'
weight = 10

[[menus.top]]
name = 'Angebot'
pageRef = '/'
weight = 20

[[menus.top]]
name = 'Portfolio'
pageRef = '/'
weight = 30

[[menus.top]]
name = 'Kontakt'
pageRef = '/'
weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = "0.119.0"